### PR TITLE
Add support for Golang 1.15.4

### PR DESCRIPTION
**Pull request by kvch**
In Golang 1.15 `darwin/386` is not supported anymore. Thus, I have dropped it from the new Makefile.

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

**Comment by v1v** [comment]
I see some failures in the publishing

```
[2020-11-09T16:45:36.771Z] 1.15.4-arm: digest: sha256:4b8220b64af4137fec93ea89793b9bb2e170676820670d9ece382bf4e3138bec size: 2207

[2020-11-09T16:45:36.771Z] make[2]: Leaving directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15/arm'

[2020-11-09T16:45:36.771Z] make[2]: Entering directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15/mips'

[2020-11-09T16:45:36.771Z] echo ">> Pushing docker.elastic.co/observability-ci/golang-crossbuild:1.15.4-mips"

[2020-11-09T16:45:36.771Z] >> Pushing docker.elastic.co/observability-ci/golang-crossbuild:1.15.4-mips

[2020-11-09T16:45:36.771Z] The push refers to repository [docker.elastic.co/observability-ci/golang-crossbuild]

[2020-11-09T16:45:36.771Z] tag does not exist: docker.elastic.co/observability-ci/golang-crossbuild:1.15.4-mips

[2020-11-09T16:45:36.771Z] ..//../Makefile.common:9: recipe for target 'push' failed

[2020-11-09T16:45:36.771Z] make[2]: *** [push] Error 1

[2020-11-09T16:45:36.771Z] make[2]: Leaving directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15/mips'

[2020-11-09T16:45:36.771Z] Makefile:8: recipe for target 'push' failed

[2020-11-09T16:45:36.771Z] make[1]: *** [push] Error 1

[2020-11-09T16:45:36.771Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15'

[2020-11-09T16:45:36.771Z] make[1]: Entering directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15'

[2020-11-09T16:45:36.771Z] make[2]: Entering directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.15/base'

[2020-11-09T16:45:36.771Z] echo ">> Pushing docker.elastic.co/observability-ci/golang-crossbuild:1.15.4-base-debian7"
```

**Review by v1v — CHANGES_REQUESTED** [review]
I see some failures in the publishing stage

```


[2020-11-09T16:30:17.820Z] echo ">> Pushing docker.elastic.co/observability-ci/golang-crossbuild:1.13.10-mips"

[2020-11-09T16:30:17.820Z] >> Pushing docker.elastic.co/observability-ci/golang-crossbuild:1.13.10-mips

[2020-11-09T16:30:17.820Z] The push refers to repository [docker.elastic.co/observability-ci/golang-crossbuild]

[2020-11-09T16:30:17.820Z] tag does not exist: docker.elastic.co/observability-ci/golang-crossbuild:1.13.10-mips

[2020-11-09T16:30:17.820Z] ..//../Makefile.common:9: recipe for target 'push' failed

[2020-11-09T16:30:17.820Z] make[2]: *** [push] Error 1

[2020-11-09T16:30:17.820Z] make[2]: Leaving directory '/var/lib/jenkins/workspace/eats_golang-crossbuild-mbp_PR-68/src/github.com/elastic/golang-crossbuild/go1.13/mips'

[2020-11-09T16:30:17.820Z] Makefile:8: recipe for target 'push' failed

[2020-11-09T16:30:17.820Z] make[1]: *** [push] Error 1
```

https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fgolang-crossbuild-mbp/detail/PR-68/1/pipeline/104#step-156-log-1199

**Comment by v1v** [comment]
You can use the CLI

```bash
$ curl -s 'https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/pipelines/golang-crossbuild-mbp/branches/PR-68/runs/1/nodes/104/log/?start=0' | grep failed -B 5
```


And I see another one when building the docker image:

```
[2020-11-09T15:53:25.464Z]  ---> efa0a4251391
[2020-11-09T15:53:25.464Z] Step 4/10 : RUN     dpkg --add-architecture mips64el     && apt-get update -qq     && apt-get install -qq -y       --no-install-recommends       --allow-unauthenticated         crossbuild-essential-mipsel         gcc-mips-linux-gnu         g++-mips-linux-gnu         gcc-6-mips64-linux-gnuabi64         g++-6-mips64-linux-gnuabi64         gcc-6-mips64el-linux-gnuabi64         g++-6-mips64el-linux-gnuabi64         librpm-dev:mips64el         libc-dev:mips64el         libpopt-dev:mips64el         linux-libc-dev:mips64el         libxml2-dev:mips64el         libxml2:mips64el         libicu-dev:mips64el         libicu57:mips64el         icu-devtools:mips64el         libsystemd-dev:mips64el     && rm -rf /var/lib/apt/lists/*
[2020-11-09T15:53:25.464Z]  ---> Running in 998abc42f95f
[2020-11-09T15:53:33.596Z] E: Unable to correct problems, you have held broken packages.
[2020-11-09T15:53:33.596Z] The command '/bin/sh -c dpkg --add-architecture mips64el     && apt-get update -qq     && apt-get install -qq -y       --no-install-recommends       --allow-unauthenticated         crossbuild-essential-mipsel         gcc-mips-linux-gnu         g++-mips-linux-gnu         gcc-6-mips64-linux-gnuabi64         g++-6-mips64-linux-gnuabi64         gcc-6-mips64el-linux-gnuabi64         g++-6-mips64el-linux-gnuabi64         librpm-dev:mips64el         libc-dev:mips64el         libpopt-dev:mips64el         linux-libc-dev:mips64el         libxml2-dev:mips64el         libxml2:mips64el         libicu-dev:mips64el         libicu57:mips64el         icu-devtools:mips64el         libsystemd-dev:mips64el     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[2020-11-09T15:53:33.596Z] ../Makefile.common:13: recipe for target 'build' failed
```

**Comment by kvch** [comment]
Thanks I will look into the problem.

**Comment by kvch** [comment]
I am not sure how this is related. I am adding new images with Golang 1.15.4. The issue seems to be with 1.13.

**Comment by v1v** [comment]
For the record, I ran the some CLI for the master build and I did not see any failures:

```bash
$ curl -s 'https://beats-ci.elastic.co/job/Beats/job/golang-crossbuild-mbp/job/master/16/consoleText' | grep failed 
```

I'm working on populating the errorlevel to the CI since it seems the current makefiles are not doing it -> https://github.com/elastic/golang-crossbuild/pull/69

**Comment by kvch** [comment]
It seems that my changes are unrelated to the issue you have described according to https://github.com/elastic/golang-crossbuild/pull/69

**Comment by v1v** [comment]
There are still some failures:

``` bash
$ curl -s 'https://beats-ci.elastic.co/job/Beats/job/golang-crossbuild-mbp/job/PR-68/2/consoleText' | grep failed
[2020-11-10T10:03:36.643Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:03:36.643Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:12:04.547Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:12:04.547Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:20:07.881Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:20:07.881Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:24:49.511Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:24:49.511Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:25:01.375Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:25:01.376Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:25:13.749Z] ../Makefile.common:13: recipe for target 'build' failed
[2020-11-10T10:25:13.749Z] Makefile:4: recipe for target 'build' failed
[2020-11-10T10:58:09.080Z] ..//../Makefile.common:9: recipe for target 'push' failed
[2020-11-10T10:58:09.080Z] Makefile:8: recipe for target 'push' failed
[2020-11-10T11:05:49.650Z] ..//../Makefile.common:9: recipe for target 'push' failed
[2020-11-10T11:05:49.650Z] Makefile:8: recipe for target 'push' failed
[2020-11-10T11:13:23.668Z] ..//../Makefile.common:9: recipe for target 'push' failed
[2020-11-10T11:13:23.668Z] Makefile:8: recipe for target 'push' failed
```

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by kuisathaverat** [comment]
These two issues resolve all architecture and package issues we have, we only have to update them to the new go version, I suggest to close this PR and allow us to bump the go version and merge https://github.com/elastic/golang-crossbuild/pull/62 to resolve the primary issue here, and them re-work and merge https://github.com/elastic/golang-crossbuild/pull/65 to create one Docker image by architecture, now we are mixing little-endian, endia-little, 64bits, and 32bit architectures in the same container

**Comment by kuisathaverat** [comment]
I have rework #65 and #68 (This PR) on https://github.com/elastic/golang-crossbuild/pull/72

**Comment by kvch** [comment]
I am closing it in favour of #72

**Pull request closed without merging**
