### PR TITLE
Disable automatic APT updates and clear cache

### PR DESCRIPTION
**Pull request by florianl**
- Automatic APT updates can introduce an overhead when running the docker image. This results in additional noise. So disabling it shifts the focus on the task of the docker container. In addition it helps to create reproducible builds as the dependencies do not change automatically without intention. 

- Clearing the APT cache reduces the size of the docker image.

### CODE REVIEW

**Review by AndersonQ — APPROVED** [review]

**Review by ph — APPROVED** [review]

**Comment by ph** [comment]
@mergifyio update

**Comment by ph** [comment]
interesting error on the CI, we don't build explicitely for `armel` platform I am confused why the cross build docker would require them? @andrewkroh Do you remember what it's needed here?

**Comment by andrewkroh** [comment]
> interesting error on the CI, we don't build explicitely for armel platform I am confused why the cross build docker would require them?

I'm parsing this as "we don't build [beats/agent] explicitly for armel platform . . ." If someone wanted to target linux/arm (v5 or v6) then the image would need to exist. I'd be curious to see how often the armel image is downloaded if we have those metrics from our docker registry. My guess is that most arm usage is on arm (v7) (aka armhf) and arm64.

**Comment by florianl** [comment]
Closing this PR, as I'm not able to fix the CI issue atm.

**Pull request closed without merging**
